### ISSUE TITLE
configure and make does not successfully build and install

### ISSUE THREAD

**Issue by rpgoldman** [vangelisv/thea#35]
When I try to run `make install` after `configure` and `make`, I get these errors:

```
rpg@rpg-macbook-pro: ~/src/thea $ ./configure --prefix /usr/local/stow/thea
checking for swi-prolog... no
checking for swipl... swipl
configure: checking "Running swipl --dump-runtime-variables"...
"		PLBASE=/usr/local/Cellar/swi-prolog/8.0.3_1/libexec/lib/swipl"
"		PLARCH=x86_64-darwin"
checking for gmake... gmake
checking for a BSD-compatible install... /usr/local/bin/ginstall -c
configure: creating ./config.status
config.status: creating Makefile
rpg@rpg-macbook-pro: ~/src/thea $ make
Nothing to do for this package
rpg@rpg-macbook-pro: ~/src/thea $ make install
make: *** No rule to make target `owl2_basic_reasoner.pl', needed by `install'.  Stop.
```

Using `gmake` instead of `make` fails with the same error.

**Comment by tduval-unifylogic** [comment]
@cmungall  @JanWielemaker 

any suggestions on this? I'm receiving the same error. 

My plan is to test both ClioPatria and Thea (in a Pengine) as potential additions/components to a product architecture. 

attempting on: Mac Mini M1 Apple Silicon

**Comment by rpgoldman** [comment]
> @cmungall @JanWielemaker
> 
> any suggestions on this? I'm receiving the same error.
> 
> My plan is to test both ClioPatria and Thea (in a Pengine) as potential additions/components to a product architecture.
> 
> attempting on: Mac Mini M1 Apple Silicon

I am very much afraid Thea has been abandoned. The last closed issue was closed more than ten years ago. I’m closing this issue on the assumption it’s never going to be addressed

**Comment by tduval-unifylogic** [comment]
Thanks Jan,

I thought so…just thought it wouldn’t hurt to check!
